### ISSUE TITLE
Invalid ScriptableObject creation.

### ISSUE THREAD

**Issue by tobiasbu** [Lawendt/UnityLawUtilities#5]
I was using your utilities for ScriptableObject creation. Then a I get this error:

```csharp

Assertion failed on expression: '!(o->TestHideFlag(Object::kDontSaveInEditor) && (options & kAllowDontSaveObjectsToBePersistent) == 0)'
UnityEditor.AssetDatabase:CreateAsset()
LUT.ScriptableObjectDrawer:CreateAssetWithSavePrompt(Type, String) (at Assets/Scripts/LUT/Editor/ScriptableObjects/ExtendedScriptableObjectDrawer.cs:95)
LUT.ScriptableObjectDrawer:OnGUI(Rect, SerializedProperty, GUIContent) (at Assets/Scripts/LUT/Editor/ScriptableObjects/ExtendedScriptableObjectDrawer.cs:78)
UnityEditor.Editor:DrawDefaultInspector()
LUT.ObjectEditor:OnInspectorGUI() (at Assets/Scripts/LUT/Editor/CustomAttributes/EasyButtons/ButtonEditor.cs:15)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

This happens when I try to create a new ScriptableObject (in this button below).

![image](https://user-images.githubusercontent.com/3925418/52190729-ed34b200-2827-11e9-816d-8dd1c4e04d1d.png)

**Comment by Lawendt** [comment]
This is probably an error on `GizmoParameters`. Is the SO created even thought the error is thrown?

**Comment by tobiasbu** [comment]
It's creating a corrupted SO. So the problem is around the `hideFlags` property in the SO. Thanks for your time. 😄
